// Built-in spec library for feature-by-feature comparisons — the Nissan lineup
// and its most common cross-shops, Canadian market, 2026 model year. Values
// are approximate (MSRPs move, trims differ) and every rendering of them
// carries a "verify current specs" disclaimer; they exist to frame the
// conversation, not to be a contract.
//
// 2026 notes baked in: Sentra is the new generation, Rogue adds a Plug-in
// Hybrid, the Leaf is the all-new crossover EV, Altima ended after 2025 (so
// it's not listed), and Toyota's RAV4 is all-new and hybrid-only.
//
// Fields: msrp (CAD, from), engine, hp, torque (lb-ft), trans, fuel (combined
// L/100km), fuelReq, drive, clearance (mm), seats, cargo (litres behind rear
// seats), tow (lb), heated, screen, adas, warranty, features.

export const SPEC_LIBRARY = [
  // --- Nissan ---
  { id: "kicks26", make: "Nissan", label: "2026 Nissan Kicks", msrp: 28000, engine: "2.0L 4-cyl", hp: 141, torque: 140, trans: "CVT", fuel: 7.7, fuelReq: "Regular", drive: "FWD (AWD avail.)", clearance: 206, seats: 5, cargo: 850, tow: null, heated: "Seats & wheel avail.", screen: "Up to dual 12.3\"", adas: "Safety Shield 360 std", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Dual 12.3\" displays, wireless CarPlay, big style for the money" },
  { id: "sentra26", make: "Nissan", label: "2026 Nissan Sentra", msrp: 25000, engine: "2.0L 4-cyl", hp: 149, torque: 146, trans: "CVT", fuel: 7.0, fuelReq: "Regular", drive: "FWD", clearance: 140, seats: 5, cargo: 405, tow: null, heated: "Seats & wheel avail.", screen: "Up to 12.3\"", adas: "Safety Shield 360 std", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "All-new generation, upscale cabin for the class" },
  { id: "rogue26", make: "Nissan", label: "2026 Nissan Rogue", msrp: 35000, engine: "1.5L VC-Turbo", hp: 201, torque: 225, trans: "CVT", fuel: 7.3, fuelReq: "Regular", drive: "AWD avail.", clearance: 211, seats: 5, cargo: 1030, tow: 1350, heated: "Seats & wheel std from SV", screen: "Up to 12.3\" + Google built-in", adas: "Safety Shield 360 std; ProPILOT avail.", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "ProPILOT Assist, Google built-in, class-leading torque" },
  { id: "roguephev26", make: "Nissan", label: "2026 Nissan Rogue Plug-in Hybrid", msrp: 46000, engine: "2.4L PHEV", hp: 248, torque: 245, trans: "e-CVT", fuel: 3.3, fuelReq: "Regular", drive: "AWD standard", clearance: 211, seats: 5, cargo: 950, tow: 1500, heated: "Seats & wheel std", screen: "12.3\"", adas: "Full suite std", warranty: "3 yr/60,000 km (8/160 battery)", features: "~60 km electric range, AWD standard" },
  { id: "murano26", make: "Nissan", label: "2026 Nissan Murano", msrp: 44000, engine: "2.0L VC-Turbo", hp: 241, torque: 260, trans: "9-speed auto", fuel: 9.5, fuelReq: "Regular", drive: "AWD", clearance: 211, seats: 5, cargo: 900, tow: 1500, heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "ProPILOT Assist", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Premium interior, massaging seats avail." },
  { id: "pathfinder26", make: "Nissan", label: "2026 Nissan Pathfinder", msrp: 48000, engine: "3.5L V6", hp: 284, torque: 259, trans: "9-speed auto", fuel: 10.2, fuelReq: "Regular", drive: "4WD", clearance: 179, seats: 8, cargo: 470, tow: 6000, heated: "Seats & wheel std", screen: "Up to 12.3\"", adas: "Safety Shield 360 std; ProPILOT avail.", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Refreshed for 2026, 6,000 lb towing, 8 seats" },
  { id: "frontier26", make: "Nissan", label: "2026 Nissan Frontier", msrp: 45000, engine: "3.8L V6", hp: 310, torque: 281, trans: "9-speed auto", fuel: 11.6, fuelReq: "Regular", drive: "4x4", clearance: 245, seats: 5, cargo: null, tow: 6720, heated: "Seats avail.", screen: "Up to 12.3\"", adas: "Safety Shield 360 std", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "310 hp standard V6, 6,720 lb towing" },
  { id: "leaf26", make: "Nissan", label: "2026 Nissan Leaf (EV)", msrp: 42000, engine: "Electric", hp: 214, torque: 261, trans: "Single-speed", fuel: 2.0, fuelReq: "Electric", drive: "FWD", clearance: 150, seats: 5, cargo: 668, tow: null, heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "ProPILOT avail.", warranty: "3 yr/60,000 km (8/160 battery)", features: "All-new crossover design, up to ~488 km range, NACS port" },
  { id: "ariya26", make: "Nissan", label: "2026 Nissan Ariya (EV)", msrp: 48000, engine: "Electric (single/dual motor)", hp: 389, torque: 442, trans: "Single-speed", fuel: 2.2, fuelReq: "Electric", drive: "AWD avail. (e-4ORCE)", clearance: 180, seats: 5, cargo: 646, tow: null, heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "ProPILOT Assist std", warranty: "3 yr/60,000 km (8/160 battery)", features: "Up to ~465 km range, e-4ORCE AWD" },

  // --- Compact SUVs (Rogue cross-shops) ---
  { id: "rav426", make: "Toyota", label: "2026 Toyota RAV4", msrp: 38000, engine: "2.5L hybrid (hybrid-only lineup)", hp: 236, torque: null, trans: "e-CVT", fuel: 5.8, fuelReq: "Regular", drive: "AWD avail.", clearance: 211, seats: 5, cargo: 1059, tow: 1750, heated: "Seats avail.", screen: "Up to 12.9\"", adas: "Toyota Safety Sense 4.0", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "All-new generation, hybrid only" },
  { id: "crv26", make: "Honda", label: "2026 Honda CR-V", msrp: 39000, engine: "1.5L turbo (hybrid avail.)", hp: 190, torque: 179, trans: "CVT", fuel: 7.9, fuelReq: "Regular", drive: "AWD", clearance: 198, seats: 5, cargo: 1113, tow: 1500, heated: "Seats std (Canada)", screen: "Up to 9\"", adas: "Honda Sensing", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Big cargo hold, strong resale" },
  { id: "tucson26", make: "Hyundai", label: "2026 Hyundai Tucson", msrp: 34000, engine: "2.5L 4-cyl", hp: 187, torque: 178, trans: "8-speed auto", fuel: 8.1, fuelReq: "Regular", drive: "AWD avail.", clearance: 181, seats: 5, cargo: 1095, tow: 2000, heated: "Seats std (Canada)", screen: "Up to 12.3\"", adas: "SmartSense", warranty: "5 yr/100,000 km comprehensive", features: "5-yr warranty, roomy cabin" },
  { id: "cx526", make: "Mazda", label: "2026 Mazda CX-5", msrp: 35000, engine: "2.5L 4-cyl", hp: 187, torque: 186, trans: "Automatic", fuel: 8.8, fuelReq: "Regular", drive: "AWD standard", clearance: 210, seats: 5, cargo: 900, tow: 2000, heated: "Seats & wheel std", screen: "15.6\"", adas: "i-Activsense", warranty: "3 yr unlimited km (5 unlimited powertrain)", features: "All-new generation, standard AWD, huge screen" },
  { id: "equinox26", make: "Chevrolet", label: "2026 Chevrolet Equinox", msrp: 34000, engine: "1.5L turbo", hp: 175, torque: 203, trans: "CVT / 8-speed (AWD)", fuel: 8.3, fuelReq: "Regular", drive: "AWD avail.", clearance: 196, seats: 5, cargo: 845, tow: 1500, heated: "Seats avail.", screen: "11.3\" std", adas: "Chevy Safety Assist", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Big standard screen" },

  // --- Compact cars (Sentra cross-shops) ---
  { id: "corolla26", make: "Toyota", label: "2026 Toyota Corolla", msrp: 26000, engine: "2.0L 4-cyl", hp: 169, torque: 151, trans: "CVT", fuel: 6.7, fuelReq: "Regular", drive: "FWD", clearance: 130, seats: 5, cargo: 371, tow: null, heated: "Seats avail.", screen: "8\"", adas: "Toyota Safety Sense 3.0", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Reliability reputation, strong resale" },
  { id: "civic26", make: "Honda", label: "2026 Honda Civic", msrp: 29000, engine: "2.0L 4-cyl (hybrid avail.)", hp: 150, torque: 138, trans: "CVT", fuel: 7.0, fuelReq: "Regular", drive: "FWD", clearance: 127, seats: 5, cargo: 419, tow: null, heated: "Seats std (Canada)", screen: "Up to 9\"", adas: "Honda Sensing", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Refined drive, strong resale" },
  { id: "elantra26", make: "Hyundai", label: "2026 Hyundai Elantra", msrp: 25000, engine: "2.0L 4-cyl", hp: 147, torque: 132, trans: "CVT (IVT)", fuel: 6.8, fuelReq: "Regular", drive: "FWD", clearance: 140, seats: 5, cargo: 402, tow: null, heated: "Seats std (Canada)", screen: "Up to 10.25\"", adas: "SmartSense", warranty: "5 yr/100,000 km comprehensive", features: "5-yr warranty, bold styling" },
  { id: "mazda326", make: "Mazda", label: "2026 Mazda3", msrp: 27000, engine: "2.5L 4-cyl", hp: 191, torque: 186, trans: "6-speed auto", fuel: 7.9, fuelReq: "Regular", drive: "FWD (AWD avail.)", clearance: 140, seats: 5, cargo: 374, tow: null, heated: "Seats & wheel std", screen: "Up to 10.25\"", adas: "i-Activsense", warranty: "3 yr unlimited km (5 unlimited powertrain)", features: "Upscale cabin, AWD available" },

  // --- Subcompact SUVs (Kicks cross-shops) ---
  { id: "hrv26", make: "Honda", label: "2026 Honda HR-V", msrp: 32000, engine: "2.0L 4-cyl", hp: 158, torque: 138, trans: "CVT", fuel: 8.0, fuelReq: "Regular", drive: "AWD avail.", clearance: 195, seats: 5, cargo: 691, tow: null, heated: "Seats std (Canada)", screen: "Up to 9\"", adas: "Honda Sensing", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Roomy rear seat" },
  { id: "kona26", make: "Hyundai", label: "2026 Hyundai Kona", msrp: 28000, engine: "2.0L 4-cyl", hp: 147, torque: 132, trans: "CVT (IVT)", fuel: 7.4, fuelReq: "Regular", drive: "AWD avail.", clearance: 170, seats: 5, cargo: 723, tow: null, heated: "Seats std (Canada)", screen: "Dual 12.3\"", adas: "SmartSense", warranty: "5 yr/100,000 km comprehensive", features: "5-yr warranty, big screens" },

  // --- 3-row SUVs (Pathfinder cross-shops) ---
  { id: "highlander26", make: "Toyota", label: "2026 Toyota Highlander", msrp: 49000, engine: "2.4L turbo", hp: 265, torque: 310, trans: "8-speed auto", fuel: 9.8, fuelReq: "Regular", drive: "AWD", clearance: 203, seats: 8, cargo: 456, tow: 5000, heated: "Seats std", screen: "Up to 12.3\"", adas: "Toyota Safety Sense 2.5+", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Strong resale" },
  { id: "pilot26", make: "Honda", label: "2026 Honda Pilot", msrp: 52000, engine: "3.5L V6", hp: 285, torque: 262, trans: "10-speed auto", fuel: 11.0, fuelReq: "Regular", drive: "AWD", clearance: 184, seats: 8, cargo: 527, tow: 5000, heated: "Seats std", screen: "Up to 9\"", adas: "Honda Sensing", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Roomy third row" },

  // --- Midsize trucks (Frontier cross-shops) ---
  { id: "tacoma26", make: "Toyota", label: "2026 Toyota Tacoma", msrp: 47000, engine: "2.4L turbo", hp: 278, torque: 317, trans: "8-speed auto", fuel: 10.5, fuelReq: "Regular", drive: "4x4", clearance: 240, seats: 5, cargo: null, tow: 6500, heated: "Seats avail.", screen: "Up to 14\"", adas: "Toyota Safety Sense 3.0", warranty: "3 yr/60,000 km (5/100 powertrain)", features: "Off-road trim depth" },
];

export const SPEC_DISCLAIMER = "2026 model year, base trims, Canadian market — specs and pricing are approximate; confirm current details at the dealership.";
