// Built-in vehicle database for feature-by-feature comparisons — the Nissan
// lineup and the mainstream Canadian market it competes with, 2026 model year,
// ~50 vehicles across every segment. Values are curated approximations (base
// trims; MSRPs and details move during the year) and every rendering carries a
// "verify current specs" disclaimer; they frame the conversation, they're not
// a quote sheet.
//
// Fields: msrp (CAD, from) · engine · hp · torque (lb-ft) · trans · fuel /
// fuelCity / fuelHwy (L/100km) · fuelReq · range (km, EV/PHEV electric) ·
// tank (L) · drive · clearance (mm) · length (mm) · seats · cargo /
// cargoMax (L, behind rear seats / seats folded) · tow (lb) · carplay ·
// heated · screen · adas · blindSpot · rearAeb · cam360 · airbags ·
// safetyRating (IIHS, year noted) · warranty · features.

const W_NIS = "3 yr/60,000 km (5/100 powertrain)";
const W_NIS_EV = "3 yr/60,000 km (8/160 battery)";
const W_TOY = "3 yr/60,000 km (5/100 powertrain)";
const W_HON = "3 yr/60,000 km (5/100 powertrain)";
const W_HYU = "5 yr/100,000 km comprehensive";
const W_KIA = "5 yr/100,000 km comprehensive";
const W_MAZ = "3 yr unlimited km (5 unlimited powertrain)";
const W_GM  = "3 yr/60,000 km (5/100 powertrain)";
const W_FRD = "3 yr/60,000 km (5/100 powertrain)";
const W_VW  = "4 yr/80,000 km comprehensive";
const W_SUB = "3 yr/60,000 km (5/100 powertrain)";
const W_MIT = "5 yr/100,000 km (10/160 powertrain)";
const W_TES = "4 yr/80,000 km (8/192 battery)";

export const SPEC_LIBRARY = [
  // ============ NISSAN ============
  { id: "kicks26", make: "Nissan", label: "2026 Nissan Kicks", msrp: 27198, engine: "2.0L 4-cyl", hp: 141, torque: 140, trans: "CVT", fuel: 7.7, fuelCity: 8.1, fuelHwy: 7.2, fuelReq: "Regular", tank: 47, drive: "FWD (AWD avail.)", clearance: 206, length: 4366, seats: 5, cargo: 850, cargoMax: 1435, tow: null, carplay: "Wireless, standard", heated: "Seats & wheel avail.", screen: "Up to dual 12.3\"", adas: "Safety Shield 360 std", blindSpot: "Standard", rearAeb: "Standard", cam360: "Avail. (SR)", airbags: 10, safetyRating: null, warranty: W_NIS, features: "Dual 12.3\" displays, big style for the money", trims: [{"name": "S FWD", "msrp": 27198, "adds": "Base — Safety Shield 360", "set": {"drive": "FWD"}}, {"name": "S AWD", "msrp": 29198, "adds": "Base + all-wheel drive", "set": {"drive": "AWD", "fuel": 8.2, "fuelCity": 8.7, "fuelHwy": 7.6}}, {"name": "SV FWD", "msrp": 29698, "adds": "Dual 12.3\" displays, wireless CarPlay, heated seats & wheel", "set": {"drive": "FWD", "heated": "Seats & wheel std"}}, {"name": "SV AWD", "msrp": 31698, "adds": "SV + all-wheel drive", "set": {"drive": "AWD", "heated": "Seats & wheel std", "fuel": 8.2, "fuelCity": 8.7, "fuelHwy": 7.6}}, {"name": "SR FWD", "msrp": 32698, "adds": "Bose 10-speaker, around-view monitor, wireless charging, 19\" wheels", "set": {"drive": "FWD", "heated": "Seats & wheel std"}}, {"name": "SR AWD", "msrp": 34698, "adds": "SR + all-wheel drive", "set": {"drive": "AWD", "heated": "Seats & wheel std", "fuel": 8.2, "fuelCity": 8.7, "fuelHwy": 7.6}}] },
  { id: "sentra26", make: "Nissan", label: "2026 Nissan Sentra", msrp: 25268, engine: "2.0L 4-cyl", hp: 149, torque: 146, trans: "CVT", fuel: 7.0, fuelCity: 7.5, fuelHwy: 6.4, fuelReq: "Regular", tank: 47, drive: "FWD", clearance: 140, length: 4656, seats: 5, cargo: 405, cargoMax: null, tow: null, carplay: "Wireless, standard", heated: "Seats & wheel avail.", screen: "Up to 12.3\"", adas: "Safety Shield 360 std", blindSpot: "Standard", rearAeb: "Standard", cam360: "Avail. (SR)", airbags: 10, safetyRating: "Not yet rated (all-new)", warranty: W_NIS, features: "All-new generation, upscale cabin for the class", trims: [{"name": "S", "msrp": 25268, "adds": "Base — Safety Shield 360, wireless CarPlay"}, {"name": "SV", "msrp": 27768, "adds": "Dual 12.3\" displays, heated seats & wheel, remote start", "set": {"heated": "Seats & wheel std"}}, {"name": "SR", "msrp": 30268, "adds": "Sport styling, 18\" wheels, sunroof avail., premium audio", "set": {"heated": "Seats & wheel std"}}] },
  { id: "rogue26", make: "Nissan", label: "2026 Nissan Rogue", msrp: 34848, engine: "1.5L VC-Turbo 3-cyl", hp: 201, torque: 225, trans: "CVT", fuel: 7.3, fuelCity: 7.7, fuelHwy: 6.9, fuelReq: "Regular", tank: 55, drive: "AWD avail.", clearance: 211, length: 4649, seats: 5, cargo: 1030, cargoMax: 2098, tow: 1350, carplay: "Wireless, standard", heated: "Seats & wheel std from SV", screen: "Up to 12.3\" + Google built-in", adas: "Safety Shield 360 std; ProPILOT avail.", blindSpot: "Standard", rearAeb: "Standard", cam360: "Avail. (SL+)", airbags: 10, safetyRating: "IIHS TSP+ (2025)", warranty: W_NIS, features: "ProPILOT Assist, Google built-in, class-leading torque", trims: [{"name": "S FWD", "msrp": 34848, "adds": "Base — Safety Shield 360", "set": {"drive": "FWD"}}, {"name": "S AWD", "msrp": 36848, "adds": "Base + all-wheel drive", "set": {"drive": "AWD", "fuel": 7.6, "fuelCity": 8.1, "fuelHwy": 7.0}}, {"name": "SV AWD", "msrp": 38848, "adds": "AWD, heated seats & wheel, power liftgate, ProPILOT Assist", "set": {"drive": "AWD", "heated": "Seats & wheel std", "fuel": 7.6, "fuelCity": 8.1, "fuelHwy": 7.0}}, {"name": "Rock Creek AWD", "msrp": 41598, "adds": "AWD, all-terrain tires, tubular roof rails, waterproof seats", "set": {"drive": "AWD", "heated": "Seats & wheel std", "fuel": 7.8}}, {"name": "SL AWD", "msrp": 43848, "adds": "AWD, leather, 12.3\" screen + Google built-in, around-view", "set": {"drive": "AWD", "heated": "Seats & wheel std", "screen": "12.3\" + Google built-in", "fuel": 7.6}}, {"name": "Platinum AWD", "msrp": 46848, "adds": "AWD, quilted leather, ProPILOT with Navi-link, Bose, head-up display", "set": {"drive": "AWD", "heated": "Seats & wheel std", "screen": "12.3\" + Google built-in, HUD", "fuel": 7.6}}] },
  { id: "roguephev26", make: "Nissan", label: "2026 Nissan Rogue Plug-in Hybrid", msrp: 58698, engine: "2.4L 4-cyl PHEV", hp: 248, torque: 245, trans: "e-CVT", fuel: 3.3, fuelCity: null, fuelHwy: null, fuelReq: "Regular", range: 60, tank: 42, drive: "AWD standard", clearance: 211, length: 4710, seats: 5, cargo: 950, cargoMax: 1900, tow: 1500, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "12.3\"", adas: "Full suite std", blindSpot: "Standard", rearAeb: "Standard", cam360: "Standard", airbags: 8, safetyRating: null, warranty: W_NIS_EV, features: "~60 km electric range, AWD standard" },
  { id: "murano26", make: "Nissan", label: "2026 Nissan Murano", msrp: 58498, engine: "2.0L VC-Turbo", hp: 241, torque: 260, trans: "9-speed auto", fuel: 9.5, fuelCity: 10.6, fuelHwy: 8.4, fuelReq: "Regular", tank: 68, drive: "AWD", clearance: 211, length: 4897, seats: 5, cargo: 900, cargoMax: 1800, tow: 1500, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "ProPILOT Assist", blindSpot: "Standard", rearAeb: "Standard", cam360: "Standard", airbags: 10, safetyRating: null, warranty: W_NIS, features: "Premium interior, massaging seats avail.", trims: [{"name": "SV", "msrp": 58498, "adds": "Base — AWD, dual 12.3\" displays, heated seats & wheel"}, {"name": "SL", "msrp": 62498, "adds": "Leather, around-view monitor, Bose audio"}, {"name": "Platinum", "msrp": 66498, "adds": "Quilted semi-aniline leather, massaging front seats, 21\" wheels"}] },
  { id: "pathfinder26", make: "Nissan", label: "2026 Nissan Pathfinder", msrp: 55398, engine: "3.5L V6", hp: 284, torque: 259, trans: "9-speed auto", fuel: 10.2, fuelCity: 11.3, fuelHwy: 8.9, fuelReq: "Regular", tank: 71, drive: "4WD", clearance: 179, length: 5004, seats: 8, cargo: 470, cargoMax: 2280, tow: 6000, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Up to 12.3\"", adas: "Safety Shield 360 std; ProPILOT avail.", blindSpot: "Standard", rearAeb: "Standard", cam360: "Standard", airbags: 10, safetyRating: "IIHS TSP (2025)", warranty: W_NIS, features: "Refreshed for 2026, 6,000 lb towing, 8 seats", trims: [{"name": "SL", "msrp": 55398, "adds": "Base (Canada) — 4WD, 8 seats, heated seats & wheel"}, {"name": "Rock Creek", "msrp": 58398, "adds": "All-terrain tires, tubular roof rack, off-road tuned suspension"}, {"name": "Platinum", "msrp": 63398, "adds": "Leather, 12.3\" screen, Bose, tow package, head-up display"}] },
  { id: "frontier26", make: "Nissan", label: "2026 Nissan Frontier", msrp: 56498, engine: "3.8L V6", hp: 310, torque: 281, trans: "9-speed auto", fuel: 11.6, fuelCity: 12.6, fuelHwy: 10.4, fuelReq: "Regular", tank: 80, drive: "4x4", clearance: 245, length: 5395, seats: 5, cargo: null, cargoMax: null, tow: 6720, carplay: "Wireless, standard", heated: "Seats avail.", screen: "Up to 12.3\"", adas: "Safety Shield 360 std", blindSpot: "Standard", rearAeb: "Standard", cam360: "Avail. (PRO-4X+)", airbags: 8, safetyRating: null, warranty: W_NIS, features: "310 hp standard V6, 5- or 6-ft bed", trims: [{"name": "Crew SV 4x4", "msrp": 56498, "adds": "Base (Canada) — 310 hp V6, 4x4"}, {"name": "PRO-4X", "msrp": 62498, "adds": "Off-road: locking rear diff, Bilstein shocks, skid plates, all-terrains"}] },
  { id: "leaf26", make: "Nissan", label: "2026 Nissan Leaf (EV)", msrp: 44998, engine: "Electric, single motor", hp: 214, torque: 261, trans: "Single-speed", fuel: 2.0, fuelReq: "Electric", range: 488, tank: null, drive: "FWD", clearance: 150, length: 4404, seats: 5, cargo: 668, cargoMax: 1370, tow: null, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "ProPILOT avail.", blindSpot: "Standard", rearAeb: "Standard", cam360: "Avail. (Platinum+)", airbags: 10, safetyRating: "Not yet rated (all-new)", warranty: W_NIS_EV, features: "All-new crossover design, NACS (Tesla) charge port", trims: [{"name": "S+", "msrp": 44998, "adds": "Base — ~488 km range, NACS port"}, {"name": "SV+", "msrp": 48998, "adds": "Dual 12.3\" displays, ProPILOT Assist, heated wheel"}, {"name": "Platinum+", "msrp": 52998, "adds": "Bose, around-view, 19\" wheels, dimming panoramic roof"}] },
  { id: "ariya26", make: "Nissan", label: "2026 Nissan Ariya (EV)", msrp: 52898, engine: "Electric, single/dual motor", hp: 238, torque: 221, trans: "Single-speed", fuel: 2.2, fuelReq: "Electric", range: 348, tank: null, drive: "FWD (e-4ORCE AWD avail.)", clearance: 180, length: 4595, seats: 5, cargo: 646, cargoMax: 1690, tow: null, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "ProPILOT Assist std", blindSpot: "Standard", rearAeb: "Standard", cam360: "Avail. (SL+)", airbags: 8, safetyRating: "IIHS TSP+ (2024)", warranty: W_NIS_EV, features: "e-4ORCE AWD, premium cabin", trims: [{"name": "SV FWD", "msrp": 52898, "adds": "Base — single motor, ~348 km range", "set": {"drive": "FWD", "range": 348}}, {"name": "SL+ FWD", "msrp": 57898, "adds": "Longer-range battery (~465 km), ProPILOT Assist, panoramic roof", "set": {"drive": "FWD", "range": 465}}, {"name": "SL e-4ORCE AWD", "msrp": 60898, "adds": "Dual-motor AWD, 389 hp, ~428 km range", "set": {"drive": "AWD (e-4ORCE)", "hp": 389, "torque": 442, "range": 428}}, {"name": "Platinum+ e-4ORCE AWD", "msrp": 62898, "adds": "Dual-motor AWD, Nappa leather, Bose", "set": {"drive": "AWD (e-4ORCE)", "hp": 389, "torque": 442, "range": 428}}] },
  { id: "armada26", make: "Nissan", label: "2026 Nissan Armada", msrp: 85748, engine: "3.5L twin-turbo V6", hp: 425, torque: 516, trans: "9-speed auto", fuel: 13.5, fuelCity: 14.8, fuelHwy: 11.9, fuelReq: "Regular", tank: 98, drive: "4WD", clearance: 234, length: 5320, seats: 8, cargo: 565, cargoMax: 2825, tow: 8500, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Dual 12.3\" or 14.3\"", adas: "ProPILOT Assist", blindSpot: "Standard", rearAeb: "Standard", cam360: "Standard", airbags: 8, safetyRating: null, warranty: W_NIS, features: "All-new generation, 8,500 lb towing", trims: [{"name": "SL", "msrp": 85748, "adds": "Base — 425 hp twin-turbo V6, 4WD, 8,500 lb towing"}, {"name": "PRO-4X", "msrp": 92748, "adds": "Off-road: locking diff, skid plates, all-terrains"}, {"name": "Platinum", "msrp": 97748, "adds": "Massaging leather, 14.3\" displays, Klipsch audio"}, {"name": "NISMO", "msrp": 102748, "adds": "NISMO styling and tuning, 460 hp", "set": {"hp": 460}}] },

  // ============ COMPACT SUVs (Rogue cross-shops) ============
  { id: "rav426", make: "Toyota", label: "2026 Toyota RAV4", msrp: 37500, engine: "2.5L hybrid (hybrid-only lineup)", hp: 236, torque: null, trans: "e-CVT", fuel: 5.8, fuelCity: 5.5, fuelHwy: 6.1, fuelReq: "Regular", tank: 55, drive: "AWD standard (Canada)", clearance: 211, length: 4622, seats: 5, cargo: 1059, cargoMax: 1975, tow: 1750, carplay: "Wireless, standard", heated: "Seats avail.", screen: "Up to 12.9\"", adas: "Toyota Safety Sense 4.0", blindSpot: "Standard", rearAeb: "—", cam360: "Avail. (upper trims)", airbags: 8, safetyRating: "Not yet rated (all-new)", warranty: W_TOY, features: "All-new generation, hybrid only", trims: [{"name": "LE AWD", "msrp": 37500, "adds": "Base (Canada) — hybrid, AWD, TSS 4.0"}, {"name": "XLE", "msrp": 41500, "adds": "Dual-zone climate, power liftgate, larger screen"}, {"name": "Limited", "msrp": 46500, "adds": "Leather-trimmed, JBL, 12.9\" screen, ventilated seats"}] },
  { id: "crv26", make: "Honda", label: "2026 Honda CR-V", msrp: 36975, engine: "1.5L turbo (hybrid avail.)", hp: 190, torque: 179, trans: "CVT", fuel: 7.9, fuelCity: 8.4, fuelHwy: 7.1, fuelReq: "Regular", tank: 53, drive: "AWD", clearance: 198, length: 4694, seats: 5, cargo: 1113, cargoMax: 2166, tow: 1500, carplay: "Wired std; wireless upper trims", heated: "Seats std (Canada)", screen: "Up to 9\"", adas: "Honda Sensing", blindSpot: "Std from Sport", rearAeb: "—", cam360: "Avail. (Touring)", airbags: 10, safetyRating: "IIHS TSP+ (2025)", warranty: W_HON, features: "Big cargo hold, strong resale", trims: [{"name": "LX", "msrp": 36975, "adds": "Base — Honda Sensing"}, {"name": "Sport Hybrid", "msrp": 42500, "adds": "Hybrid (204 hp, 6.4 L/100km), heated wheel", "set": {"hp": 204, "fuel": 6.4, "engine": "2.0L hybrid"}}, {"name": "Touring Hybrid", "msrp": 48000, "adds": "Leather, Bose, wireless CarPlay, 9\" screen", "set": {"hp": 204, "fuel": 6.4, "engine": "2.0L hybrid", "carplay": "Wireless, standard"}}] },
  { id: "tucson26", make: "Hyundai", label: "2026 Hyundai Tucson", msrp: 35099, engine: "2.5L 4-cyl", hp: 187, torque: 178, trans: "8-speed auto", fuel: 8.1, fuelCity: 8.7, fuelHwy: 7.4, fuelReq: "Regular", tank: 54, drive: "AWD avail.", clearance: 181, length: 4640, seats: 5, cargo: 1095, cargoMax: 2119, tow: 2000, carplay: "Wireless, standard", heated: "Seats std (Canada)", screen: "Up to 12.3\"", adas: "SmartSense", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "Avail. (Ultimate)", airbags: 6, safetyRating: "IIHS TSP (2025)", warranty: W_HYU, features: "5-yr warranty, roomy cabin", trims: [{"name": "Essential FWD", "msrp": 35099, "adds": "Base — SmartSense, heated seats", "set": {"drive": "FWD"}}, {"name": "Essential AWD", "msrp": 37099, "adds": "Base + all-wheel drive", "set": {"drive": "AWD", "fuel": 8.4, "fuelCity": 9.0, "fuelHwy": 7.7}}, {"name": "Preferred AWD", "msrp": 39599, "adds": "Heated wheel, larger screens", "set": {"drive": "AWD", "fuel": 8.4, "fuelCity": 9.0, "fuelHwy": 7.7}}, {"name": "Ultimate Hybrid AWD", "msrp": 47799, "adds": "Hybrid (231 hp), leather, panoramic roof", "set": {"hp": 231, "fuel": 6.7, "engine": "1.6T hybrid", "drive": "AWD"}}] },
  { id: "cx526", make: "Mazda", label: "2026 Mazda CX-5", msrp: 35000, engine: "2.5L 4-cyl", hp: 187, torque: 186, trans: "Automatic", fuel: 8.8, fuelCity: 9.3, fuelHwy: 7.9, fuelReq: "Regular", tank: 58, drive: "AWD standard", clearance: 210, length: 4690, seats: 5, cargo: 900, cargoMax: 1900, tow: 2000, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "15.6\"", adas: "i-Activsense", blindSpot: "Standard", rearAeb: "Avail.", cam360: "Avail. (GT)", airbags: 8, safetyRating: "Not yet rated (all-new)", warranty: W_MAZ, features: "All-new generation, standard AWD, huge screen", trims: [{"name": "GX", "msrp": 35000, "adds": "Base — AWD standard, 15.6\" screen"}, {"name": "GS", "msrp": 38500, "adds": "Power liftgate, heated wheel, upgraded audio"}, {"name": "GT", "msrp": 43000, "adds": "Leather, Bose, panoramic roof, 360 camera"}] },
  { id: "equinox26", make: "Chevrolet", label: "2026 Chevrolet Equinox", msrp: 34000, engine: "1.5L turbo", hp: 175, torque: 203, trans: "CVT / 8-speed (AWD)", fuel: 8.3, fuelCity: 8.8, fuelHwy: 7.6, fuelReq: "Regular", tank: 57, drive: "AWD avail.", clearance: 196, length: 4652, seats: 5, cargo: 845, cargoMax: 1793, tow: 1500, carplay: "Wireless, standard", heated: "Seats avail.", screen: "11.3\" std", adas: "Chevy Safety Assist", blindSpot: "Avail.", rearAeb: "Avail. (upper trims)", cam360: "Avail. (upper trims)", airbags: null, safetyRating: null, warranty: W_GM, features: "Big standard screen" },
  { id: "forester26", make: "Subaru", label: "2026 Subaru Forester", msrp: 34195, engine: "2.5L 4-cyl (hybrid avail.)", hp: 180, torque: 178, trans: "CVT", fuel: 8.5, fuelCity: 9.0, fuelHwy: 7.9, fuelReq: "Regular", tank: 63, drive: "AWD standard", clearance: 220, length: 4670, seats: 5, cargo: 770, cargoMax: 2100, tow: 1500, carplay: "Wireless, standard", heated: "Seats std (Canada)", screen: "11.6\"", adas: "EyeSight std", blindSpot: "Std from Touring", rearAeb: "Avail. (upper trims)", cam360: "Avail. (upper trims)", airbags: 8, safetyRating: "IIHS TSP+ (2025)", warranty: W_SUB, features: "Standard AWD, best-in-class clearance", trims: [{"name": "Convenience", "msrp": 34195, "adds": "Base — AWD, EyeSight"}, {"name": "Touring", "msrp": 38295, "adds": "Power liftgate, heated wheel, larger screen"}, {"name": "Sport", "msrp": 41295, "adds": "Sport styling, X-Mode dual function, wireless charging"}] },
  { id: "sportage26", make: "Kia", label: "2026 Kia Sportage", msrp: 34000, engine: "2.5L 4-cyl", hp: 187, torque: 178, trans: "8-speed auto", fuel: 8.4, fuelCity: 9.1, fuelHwy: 7.7, fuelReq: "Regular", tank: 54, drive: "AWD avail.", clearance: 183, length: 4660, seats: 5, cargo: 1121, cargoMax: 2098, tow: 2000, carplay: "Wireless, standard", heated: "Seats std (Canada)", screen: "Up to 12.3\"", adas: "Highway Driving Assist avail.", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "Avail. (X-Line)", airbags: 6, safetyRating: null, warranty: W_KIA, features: "5-yr warranty, huge cargo", trims: [{"name": "LX FWD", "msrp": 34000, "adds": "Base — heated seats", "set": {"drive": "FWD"}}, {"name": "LX AWD", "msrp": 36000, "adds": "Base + all-wheel drive", "set": {"drive": "AWD", "fuel": 8.9, "fuelCity": 9.6, "fuelHwy": 8.1}}, {"name": "EX AWD", "msrp": 38500, "adds": "AWD, heated wheel, larger screens", "set": {"drive": "AWD", "fuel": 8.9}}, {"name": "X-Line Limited AWD", "msrp": 43500, "adds": "Rugged styling, leather, panoramic display", "set": {"drive": "AWD", "fuel": 8.9}}] },
  { id: "tiguan26", make: "Volkswagen", label: "2026 VW Tiguan", msrp: 36000, engine: "2.0L turbo", hp: 201, torque: 207, trans: "8-speed auto", fuel: 9.0, fuelCity: 9.6, fuelHwy: 8.1, fuelReq: "Regular", tank: 58, drive: "AWD (4MOTION)", clearance: 200, length: 4709, seats: 5, cargo: 1100, cargoMax: 2100, tow: 1500, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Up to 15\"", adas: "IQ.DRIVE std", blindSpot: "Standard", rearAeb: "—", cam360: "Avail. (upper trims)", airbags: null, safetyRating: "Not yet rated (all-new)", warranty: W_VW, features: "All-new generation, 4-yr warranty" },
  { id: "outlander26", make: "Mitsubishi", label: "2026 Mitsubishi Outlander", msrp: 35000, engine: "2.5L 4-cyl", hp: 181, torque: 181, trans: "CVT", fuel: 8.7, fuelCity: 9.2, fuelHwy: 8.0, fuelReq: "Regular", tank: 56, drive: "AWD (S-AWC) avail.", clearance: 210, length: 4720, seats: 7, cargo: 940, cargoMax: 2260, tow: 2000, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Up to 12.3\"", adas: "MI-PILOT avail.", blindSpot: "Standard", rearAeb: "Avail.", cam360: "Avail. (upper trims)", airbags: 8, safetyRating: "IIHS TSP+ (2024)", warranty: W_MIT, features: "10-yr powertrain warranty, standard 3rd row" },
  { id: "escape26", make: "Ford", label: "2026 Ford Escape", msrp: 34000, engine: "1.5L turbo (hybrid avail.)", hp: 180, torque: 199, trans: "8-speed auto", fuel: 8.5, fuelCity: 9.2, fuelHwy: 7.7, fuelReq: "Regular", tank: 55, drive: "AWD avail.", clearance: 198, length: 4585, seats: 5, cargo: 974, cargoMax: 1852, tow: 2000, carplay: "Wireless, standard", heated: "Seats avail.", screen: "Up to 13.2\"", adas: "Co-Pilot360", blindSpot: "Standard", rearAeb: "—", cam360: "Avail. (upper trims)", airbags: null, safetyRating: null, warranty: W_FRD, features: "Hybrid and PHEV options" },

  // ============ COMPACT CARS (Sentra cross-shops) ============
  { id: "corolla26", make: "Toyota", label: "2026 Toyota Corolla", msrp: 26000, engine: "2.0L 4-cyl", hp: 169, torque: 151, trans: "CVT", fuel: 6.7, fuelCity: 7.1, fuelHwy: 5.9, fuelReq: "Regular", tank: 50, drive: "FWD", clearance: 130, length: 4630, seats: 5, cargo: 371, cargoMax: null, tow: null, carplay: "Wired, standard", heated: "Seats avail.", screen: "8\"", adas: "Toyota Safety Sense 3.0", blindSpot: "Avail. (SE+)", rearAeb: "—", cam360: "—", airbags: 10, safetyRating: "IIHS TSP (2024)", warranty: W_TOY, features: "Reliability reputation, strong resale", trims: [{"name": "LE", "msrp": 26000, "adds": "Base — TSS 3.0"}, {"name": "SE", "msrp": 28500, "adds": "Sport styling, 18\" wheels, paddle shifters"}, {"name": "XSE", "msrp": 32000, "adds": "Leather-trimmed, JBL, larger screen"}] },
  { id: "civic26", make: "Honda", label: "2026 Honda Civic", msrp: 29000, engine: "2.0L 4-cyl (hybrid avail.)", hp: 150, torque: 138, trans: "CVT", fuel: 7.0, fuelCity: 7.3, fuelHwy: 6.3, fuelReq: "Regular", tank: 47, drive: "FWD", clearance: 127, length: 4678, seats: 5, cargo: 419, cargoMax: null, tow: null, carplay: "Wired std; wireless upper trims", heated: "Seats std (Canada)", screen: "Up to 9\"", adas: "Honda Sensing", blindSpot: "Std from Sport", rearAeb: "—", cam360: "—", airbags: 10, safetyRating: "IIHS TSP+ (2025)", warranty: W_HON, features: "Refined drive, strong resale", trims: [{"name": "LX", "msrp": 29000, "adds": "Base — Honda Sensing"}, {"name": "Sport", "msrp": 32500, "adds": "Sport styling, heated wheel, sunroof"}, {"name": "Sport Touring Hybrid", "msrp": 38500, "adds": "Hybrid (200 hp, 5.9 L/100km), leather, Bose", "set": {"hp": 200, "fuel": 5.9, "engine": "2.0L hybrid"}}] },
  { id: "elantra26", make: "Hyundai", label: "2026 Hyundai Elantra", msrp: 25000, engine: "2.0L 4-cyl", hp: 147, torque: 132, trans: "CVT (IVT)", fuel: 6.8, fuelCity: 7.1, fuelHwy: 6.2, fuelReq: "Regular", tank: 47, drive: "FWD", clearance: 140, length: 4676, seats: 5, cargo: 402, cargoMax: null, tow: null, carplay: "Wireless, standard", heated: "Seats std (Canada)", screen: "Up to 10.25\"", adas: "SmartSense", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "—", airbags: null, safetyRating: null, warranty: W_HYU, features: "5-yr warranty, bold styling", trims: [{"name": "Essential", "msrp": 25000, "adds": "Base — SmartSense"}, {"name": "Preferred", "msrp": 27500, "adds": "Heated wheel, larger screen, blind-spot"}, {"name": "Luxury", "msrp": 30500, "adds": "Leather, sunroof, dual 10.25\" screens"}] },
  { id: "mazda326", make: "Mazda", label: "2026 Mazda3", msrp: 27000, engine: "2.5L 4-cyl", hp: 191, torque: 186, trans: "6-speed auto", fuel: 7.9, fuelCity: 8.6, fuelHwy: 6.9, fuelReq: "Regular", tank: 50, drive: "FWD (AWD avail.)", clearance: 140, length: 4662, seats: 5, cargo: 374, cargoMax: null, tow: null, carplay: "Wireless avail.", heated: "Seats & wheel std", screen: "Up to 10.25\"", adas: "i-Activsense", blindSpot: "Standard", rearAeb: "Avail.", cam360: "Avail. (GT)", airbags: null, safetyRating: "IIHS TSP+ (2024)", warranty: W_MAZ, features: "Upscale cabin, AWD available" },
  { id: "k426", make: "Kia", label: "2026 Kia K4", msrp: 25000, engine: "2.0L 4-cyl", hp: 147, torque: 132, trans: "CVT (IVT)", fuel: 7.0, fuelCity: 7.4, fuelHwy: 6.3, fuelReq: "Regular", tank: 47, drive: "FWD", clearance: 140, length: 4710, seats: 5, cargo: 413, cargoMax: null, tow: null, carplay: "Wireless, standard", heated: "Seats std (Canada)", screen: "Up to dual 12.3\"", adas: "Highway Driving Assist avail.", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "—", airbags: null, safetyRating: null, warranty: W_KIA, features: "5-yr warranty, big screens" },
  { id: "jetta26", make: "Volkswagen", label: "2026 VW Jetta", msrp: 26000, engine: "1.5L turbo", hp: 158, torque: 184, trans: "8-speed auto", fuel: 6.9, fuelCity: 7.4, fuelHwy: 6.1, fuelReq: "Regular", tank: 50, drive: "FWD", clearance: 140, length: 4771, seats: 5, cargo: 399, cargoMax: null, tow: null, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "8\"", adas: "IQ.DRIVE avail.", blindSpot: "Standard", rearAeb: "—", cam360: "—", airbags: null, safetyRating: null, warranty: W_VW, features: "Turbo torque, 4-yr warranty" },

  // ============ SUBCOMPACT SUVs (Kicks cross-shops) ============
  { id: "hrv26", make: "Honda", label: "2026 Honda HR-V", msrp: 32000, engine: "2.0L 4-cyl", hp: 158, torque: 138, trans: "CVT", fuel: 8.0, fuelCity: 8.4, fuelHwy: 7.4, fuelReq: "Regular", tank: 53, drive: "AWD avail.", clearance: 195, length: 4568, seats: 5, cargo: 691, cargoMax: 1559, tow: null, carplay: "Wired std; wireless upper trims", heated: "Seats std (Canada)", screen: "Up to 9\"", adas: "Honda Sensing", blindSpot: "Std from Sport", rearAeb: "—", cam360: "—", airbags: 10, safetyRating: null, warranty: W_HON, features: "Roomy rear seat", trims: [{"name": "LX FWD", "msrp": 32000, "adds": "Base — Honda Sensing", "set": {"drive": "FWD"}}, {"name": "LX AWD", "msrp": 34300, "adds": "Base + all-wheel drive", "set": {"drive": "AWD", "fuel": 8.5, "fuelCity": 9.0, "fuelHwy": 7.9}}, {"name": "Sport AWD", "msrp": 35500, "adds": "AWD, heated wheel, roof rails", "set": {"drive": "AWD", "fuel": 8.5}}, {"name": "EX-L AWD", "msrp": 38500, "adds": "Leather, wireless CarPlay, 9\" screen", "set": {"drive": "AWD", "fuel": 8.5, "carplay": "Wireless, standard"}}] },
  { id: "kona26", make: "Hyundai", label: "2026 Hyundai Kona", msrp: 28000, engine: "2.0L 4-cyl", hp: 147, torque: 132, trans: "CVT (IVT)", fuel: 7.4, fuelCity: 7.7, fuelHwy: 6.9, fuelReq: "Regular", tank: 47, drive: "AWD avail.", clearance: 170, length: 4350, seats: 5, cargo: 723, cargoMax: 1803, tow: null, carplay: "Wireless, standard", heated: "Seats std (Canada)", screen: "Dual 12.3\"", adas: "SmartSense", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "Avail. (N Line)", airbags: null, safetyRating: null, warranty: W_HYU, features: "5-yr warranty, big screens", trims: [{"name": "Essential FWD", "msrp": 28000, "adds": "Base — dual 12.3\" screens", "set": {"drive": "FWD"}}, {"name": "Preferred FWD", "msrp": 30500, "adds": "Heated wheel, wireless charging", "set": {"drive": "FWD"}}, {"name": "Preferred AWD", "msrp": 32500, "adds": "Preferred + all-wheel drive", "set": {"drive": "AWD", "fuel": 8.0, "fuelCity": 8.5, "fuelHwy": 7.4}}, {"name": "N Line Ultimate AWD", "msrp": 35500, "adds": "Sport styling, Bose, sunroof", "set": {"drive": "AWD", "fuel": 8.0}}] },
  { id: "crosstrek26", make: "Subaru", label: "2026 Subaru Crosstrek", msrp: 30000, engine: "2.0L 4-cyl", hp: 152, torque: 145, trans: "CVT", fuel: 7.9, fuelCity: 8.3, fuelHwy: 7.2, fuelReq: "Regular", tank: 63, drive: "AWD standard", clearance: 220, length: 4480, seats: 5, cargo: 564, cargoMax: 1549, tow: 1500, carplay: "Wireless, standard", heated: "Seats std (Canada)", screen: "11.6\"", adas: "EyeSight std", blindSpot: "Std from Touring", rearAeb: "Avail.", cam360: "—", airbags: null, safetyRating: "IIHS TSP+ (2024)", warranty: W_SUB, features: "Standard AWD, 220 mm clearance" },
  { id: "seltos26", make: "Kia", label: "2026 Kia Seltos", msrp: 29000, engine: "2.0L 4-cyl", hp: 146, torque: 132, trans: "CVT (IVT)", fuel: 7.7, fuelCity: 8.1, fuelHwy: 7.1, fuelReq: "Regular", tank: 50, drive: "AWD avail.", clearance: 185, length: 4430, seats: 5, cargo: 752, cargoMax: 1778, tow: null, carplay: "Wireless, standard", heated: "Seats std (Canada)", screen: "Up to 10.25\"", adas: "Kia Drive Wise", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "—", airbags: null, safetyRating: null, warranty: W_KIA, features: "5-yr warranty, roomy for the class" },
  { id: "taos26", make: "Volkswagen", label: "2026 VW Taos", msrp: 29000, engine: "1.5L turbo", hp: 158, torque: 184, trans: "8-speed auto", fuel: 8.0, fuelCity: 8.5, fuelHwy: 7.4, fuelReq: "Regular", tank: 51, drive: "AWD avail.", clearance: 186, length: 4461, seats: 5, cargo: 705, cargoMax: 1866, tow: null, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "8\"", adas: "IQ.DRIVE std", blindSpot: "Standard", rearAeb: "—", cam360: "—", airbags: null, safetyRating: null, warranty: W_VW, features: "Turbo torque, 4-yr warranty" },
  { id: "trailblazer26", make: "Chevrolet", label: "2026 Chevrolet Trailblazer", msrp: 30000, engine: "1.3L turbo", hp: 155, torque: 174, trans: "CVT / 9-speed (AWD)", fuel: 8.2, fuelCity: 8.7, fuelHwy: 7.6, fuelReq: "Regular", tank: 51, drive: "AWD avail.", clearance: 189, length: 4410, seats: 5, cargo: 716, cargoMax: 1540, tow: null, carplay: "Wireless, standard", heated: "Seats avail.", screen: "11\" std", adas: "Chevy Safety Assist", blindSpot: "Avail.", rearAeb: "—", cam360: "Avail. (upper trims)", airbags: null, safetyRating: null, warranty: W_GM, features: "Flexible cargo, big screen" },
  { id: "corollacross26", make: "Toyota", label: "2026 Toyota Corolla Cross", msrp: 30000, engine: "2.0L 4-cyl (hybrid avail.)", hp: 169, torque: 150, trans: "CVT", fuel: 7.6, fuelCity: 7.9, fuelHwy: 7.3, fuelReq: "Regular", tank: 47, drive: "AWD avail.", clearance: 208, length: 4460, seats: 5, cargo: 750, cargoMax: 1890, tow: 1500, carplay: "Wired, standard", heated: "Seats avail.", screen: "8\"", adas: "Toyota Safety Sense 3.0", blindSpot: "Avail.", rearAeb: "—", cam360: "—", airbags: 8, safetyRating: null, warranty: W_TOY, features: "Corolla reliability in SUV form" },
  { id: "cx3026", make: "Mazda", label: "2026 Mazda CX-30", msrp: 30000, engine: "2.5L 4-cyl", hp: 191, torque: 186, trans: "6-speed auto", fuel: 8.2, fuelCity: 8.8, fuelHwy: 7.3, fuelReq: "Regular", tank: 48, drive: "AWD standard", clearance: 200, length: 4395, seats: 5, cargo: 572, cargoMax: 1280, tow: null, carplay: "Wireless avail.", heated: "Seats & wheel std", screen: "Up to 10.25\"", adas: "i-Activsense", blindSpot: "Standard", rearAeb: "Avail.", cam360: "Avail. (GT)", airbags: null, safetyRating: null, warranty: W_MAZ, features: "Standard AWD, upscale cabin" },
  { id: "trax26", make: "Chevrolet", label: "2026 Chevrolet Trax", msrp: 26000, engine: "1.2L turbo", hp: 137, torque: 162, trans: "6-speed auto", fuel: 8.0, fuelCity: 8.4, fuelHwy: 7.4, fuelReq: "Regular", tank: 42, drive: "FWD only", clearance: 185, length: 4537, seats: 5, cargo: 725, cargoMax: 1532, tow: null, carplay: "Wireless, standard", heated: "Seats avail.", screen: "Up to 11\"", adas: "Chevy Safety Assist", blindSpot: "Avail.", rearAeb: "—", cam360: "—", airbags: null, safetyRating: null, warranty: W_GM, features: "Value price — but no AWD offered" },

  // ============ MIDSIZE / 3-ROW SUVs (Pathfinder & Murano cross-shops) ============
  { id: "highlander26", make: "Toyota", label: "2026 Toyota Highlander", msrp: 49000, engine: "2.4L turbo", hp: 265, torque: 310, trans: "8-speed auto", fuel: 9.8, fuelCity: 10.3, fuelHwy: 9.0, fuelReq: "Regular", tank: 65, drive: "AWD", clearance: 203, length: 4966, seats: 8, cargo: 456, cargoMax: 2387, tow: 5000, carplay: "Wireless, standard", heated: "Seats std", screen: "Up to 12.3\"", adas: "Toyota Safety Sense 2.5+", blindSpot: "Standard", rearAeb: "—", cam360: "Avail. (Limited+)", airbags: 8, safetyRating: "IIHS TSP+ (2024)", warranty: W_TOY, features: "Strong resale" },
  { id: "pilot26", make: "Honda", label: "2026 Honda Pilot", msrp: 52000, engine: "3.5L V6", hp: 285, torque: 262, trans: "10-speed auto", fuel: 11.0, fuelCity: 11.5, fuelHwy: 9.9, fuelReq: "Regular", tank: 70, drive: "AWD", clearance: 184, length: 5085, seats: 8, cargo: 527, cargoMax: 2464, tow: 5000, carplay: "Wired std; wireless upper trims", heated: "Seats std", screen: "Up to 9\"", adas: "Honda Sensing", blindSpot: "Standard", rearAeb: "—", cam360: "Avail. (Touring+)", airbags: 10, safetyRating: "IIHS TSP+ (2025)", warranty: W_HON, features: "Roomy third row" },
  { id: "telluride26", make: "Kia", label: "2026 Kia Telluride", msrp: 52000, engine: "3.8L V6", hp: 291, torque: 262, trans: "8-speed auto", fuel: 11.2, fuelCity: 12.0, fuelHwy: 9.7, fuelReq: "Regular", tank: 71, drive: "AWD", clearance: 203, length: 5001, seats: 8, cargo: 601, cargoMax: 2455, tow: 5000, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Up to 12.3\"", adas: "Highway Driving Assist", blindSpot: "Standard", rearAeb: "Avail. (SX)", cam360: "Avail. (SX)", airbags: null, safetyRating: "IIHS TSP+ (2024)", warranty: W_KIA, features: "5-yr warranty, premium feel", trims: [{"name": "EX", "msrp": 52000, "adds": "Base — AWD, dual 12.3\" screens"}, {"name": "SX", "msrp": 57500, "adds": "Nappa leather, 360 camera, tow self-leveling"}, {"name": "SX Limited", "msrp": 61500, "adds": "Ventilated 2nd row, head-up display, premium audio"}] },
  { id: "palisade26", make: "Hyundai", label: "2026 Hyundai Palisade", msrp: 54000, engine: "3.5L V6 (hybrid avail.)", hp: 287, torque: 260, trans: "8-speed auto", fuel: 11.0, fuelCity: 11.8, fuelHwy: 9.6, fuelReq: "Regular", tank: 72, drive: "AWD", clearance: 200, length: 5060, seats: 8, cargo: 587, cargoMax: 2447, tow: 5000, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "SmartSense + HDA", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "Avail. (upper trims)", airbags: null, safetyRating: "Not yet rated (all-new)", warranty: W_HYU, features: "All-new generation, 5-yr warranty" },
  { id: "santafe26", make: "Hyundai", label: "2026 Hyundai Santa Fe", msrp: 42000, engine: "2.5L turbo (hybrid avail.)", hp: 277, torque: 311, trans: "8-speed DCT", fuel: 10.0, fuelCity: 10.5, fuelHwy: 9.2, fuelReq: "Regular", tank: 67, drive: "AWD", clearance: 177, length: 4830, seats: 7, cargo: 725, cargoMax: 2255, tow: 3500, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "SmartSense + HDA", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "Avail. (upper trims)", airbags: null, safetyRating: null, warranty: W_HYU, features: "Boxy design, huge tailgate opening" },
  { id: "sorento26", make: "Kia", label: "2026 Kia Sorento", msrp: 42000, engine: "2.5L turbo (hybrid avail.)", hp: 281, torque: 311, trans: "8-speed DCT", fuel: 9.9, fuelCity: 10.6, fuelHwy: 9.0, fuelReq: "Regular", tank: 67, drive: "AWD", clearance: 176, length: 4815, seats: 7, cargo: 357, cargoMax: 2100, tow: 3500, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "Highway Driving Assist", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "Avail. (upper trims)", airbags: null, safetyRating: null, warranty: W_KIA, features: "5-yr warranty, tidy footprint" },
  { id: "traverse26", make: "Chevrolet", label: "2026 Chevrolet Traverse", msrp: 50000, engine: "2.5L turbo", hp: 328, torque: 326, trans: "8-speed auto", fuel: 11.2, fuelCity: 11.9, fuelHwy: 10.2, fuelReq: "Regular", tank: 74, drive: "AWD avail.", clearance: 197, length: 5205, seats: 8, cargo: 651, cargoMax: 2763, tow: 5000, carplay: "Wireless, standard", heated: "Seats std", screen: "17.7\"", adas: "Chevy Safety Assist; Super Cruise avail.", blindSpot: "Avail.", rearAeb: "Avail. (upper trims)", cam360: "Avail. (upper trims)", airbags: null, safetyRating: null, warranty: W_GM, features: "Massive cargo, huge screen" },
  { id: "passport26", make: "Honda", label: "2026 Honda Passport", msrp: 52000, engine: "3.5L V6", hp: 285, torque: 262, trans: "10-speed auto", fuel: 11.5, fuelCity: 12.2, fuelHwy: 10.4, fuelReq: "Regular", tank: 70, drive: "AWD standard", clearance: 211, length: 4900, seats: 5, cargo: 1160, cargoMax: 2800, tow: 5000, carplay: "Wireless, standard", heated: "Seats std", screen: "Up to 12.3\"", adas: "Honda Sensing", blindSpot: "Standard", rearAeb: "—", cam360: "Avail. (upper trims)", airbags: 10, safetyRating: "Not yet rated (all-new)", warranty: W_HON, features: "All-new generation, rugged 2-row" },

  // ============ MIDSIZE SEDANS (Altima replacements / cross-shops) ============
  { id: "camry26", make: "Toyota", label: "2026 Toyota Camry", msrp: 34000, engine: "2.5L hybrid (hybrid-only)", hp: 225, torque: null, trans: "e-CVT", fuel: 5.3, fuelCity: 5.1, fuelHwy: 5.6, fuelReq: "Regular", tank: 50, drive: "AWD avail.", clearance: 145, length: 4920, seats: 5, cargo: 428, cargoMax: null, tow: null, carplay: "Wireless, standard", heated: "Seats avail.", screen: "Up to 12.3\"", adas: "Toyota Safety Sense 3.0", blindSpot: "Standard", rearAeb: "—", cam360: "Avail. (XLE+)", airbags: 10, safetyRating: "IIHS TSP+ (2025)", warranty: W_TOY, features: "Hybrid only, excellent economy" },
  { id: "accord26", make: "Honda", label: "2026 Honda Accord", msrp: 40000, engine: "1.5L turbo (hybrid avail.)", hp: 192, torque: 192, trans: "CVT", fuel: 7.9, fuelCity: 8.4, fuelHwy: 7.3, fuelReq: "Regular", tank: 56, drive: "FWD", clearance: 136, length: 4970, seats: 5, cargo: 473, cargoMax: null, tow: null, carplay: "Wireless upper trims", heated: "Seats std", screen: "Up to 12.3\"", adas: "Honda Sensing", blindSpot: "Standard", rearAeb: "—", cam360: "—", airbags: 10, safetyRating: "IIHS TSP+ (2025)", warranty: W_HON, features: "Refined, roomy" },

  // ============ MIDSIZE TRUCKS (Frontier cross-shops) ============
  { id: "tacoma26", make: "Toyota", label: "2026 Toyota Tacoma", msrp: 47000, engine: "2.4L turbo", hp: 278, torque: 317, trans: "8-speed auto", fuel: 10.5, fuelCity: 11.0, fuelHwy: 9.7, fuelReq: "Regular", tank: 69, drive: "4x4", clearance: 240, length: 5411, seats: 5, cargo: null, cargoMax: null, tow: 6500, carplay: "Wireless, standard", heated: "Seats avail.", screen: "Up to 14\"", adas: "Toyota Safety Sense 3.0", blindSpot: "Avail. (upper trims)", rearAeb: "—", cam360: "Avail. (upper trims)", airbags: 8, safetyRating: null, warranty: W_TOY, features: "Off-road trim depth", trims: [{"name": "SR5", "msrp": 47000, "adds": "Base — 4x4, TSS 3.0"}, {"name": "TRD Sport", "msrp": 52500, "adds": "Sport-tuned suspension, 14\" screen avail."}, {"name": "TRD Off-Road", "msrp": 55500, "adds": "Locking rear diff, Bilstein shocks, crawl control"}] },
  { id: "ranger26", make: "Ford", label: "2026 Ford Ranger", msrp: 45000, engine: "2.3L turbo", hp: 270, torque: 310, trans: "10-speed auto", fuel: 10.8, fuelCity: 11.4, fuelHwy: 9.8, fuelReq: "Regular", tank: 68, drive: "4x4", clearance: 226, length: 5360, seats: 5, cargo: null, cargoMax: null, tow: 7500, carplay: "Wireless, standard", heated: "Seats avail.", screen: "Up to 12\"", adas: "Co-Pilot360", blindSpot: "Standard", rearAeb: "—", cam360: "Avail. (Lariat)", airbags: null, safetyRating: null, warranty: W_FRD, features: "7,500 lb towing" },
  { id: "colorado26", make: "Chevrolet", label: "2026 Chevrolet Colorado", msrp: 45000, engine: "2.7L turbo", hp: 310, torque: 390, trans: "8-speed auto", fuel: 11.0, fuelCity: 11.7, fuelHwy: 10.0, fuelReq: "Regular", tank: 82, drive: "4x4", clearance: 237, length: 5410, seats: 5, cargo: null, cargoMax: null, tow: 7700, carplay: "Wireless, standard", heated: "Seats avail.", screen: "11.3\" std", adas: "Chevy Safety Assist", blindSpot: "Avail.", rearAeb: "—", cam360: "Avail. (upper trims)", airbags: null, safetyRating: null, warranty: W_GM, features: "Class-leading torque and towing" },

  // ============ EVs (Leaf & Ariya cross-shops) ============
  { id: "modely26", make: "Tesla", label: "2026 Tesla Model Y", msrp: 60000, engine: "Electric, single/dual motor", hp: 299, torque: 331, trans: "Single-speed", fuel: 1.9, fuelReq: "Electric", range: 500, tank: null, drive: "AWD avail.", clearance: 167, length: 4790, seats: 5, cargo: 854, cargoMax: 2138, tow: 3500, carplay: "No CarPlay / Android Auto", heated: "Seats & wheel std", screen: "15.4\"", adas: "Autopilot std", blindSpot: "Standard (cameras)", rearAeb: "—", cam360: "Standard (cameras)", airbags: null, safetyRating: "IIHS TSP+ (2024)", warranty: W_TES, features: "Supercharger network — but no CarPlay", trims: [{"name": "Long Range RWD", "msrp": 60000, "adds": "Base — ~500 km range"}, {"name": "Long Range AWD", "msrp": 65000, "adds": "Dual motor AWD, quicker 0-100", "set": {"drive": "AWD"}}, {"name": "Performance", "msrp": 73000, "adds": "~460 hp, lowered suspension, 21\" wheels", "set": {"hp": 460, "drive": "AWD"}}] },
  { id: "model326", make: "Tesla", label: "2026 Tesla Model 3", msrp: 55000, engine: "Electric, single/dual motor", hp: 286, torque: 310, trans: "Single-speed", fuel: 1.9, fuelReq: "Electric", range: 500, tank: null, drive: "AWD avail.", clearance: 138, length: 4720, seats: 5, cargo: 682, cargoMax: null, tow: 1000, carplay: "No CarPlay / Android Auto", heated: "Seats & wheel std", screen: "15.4\"", adas: "Autopilot std", blindSpot: "Standard (cameras)", rearAeb: "—", cam360: "Standard (cameras)", airbags: null, safetyRating: null, warranty: W_TES, features: "Efficiency king — but no CarPlay" },
  { id: "ioniq526", make: "Hyundai", label: "2026 Hyundai Ioniq 5", msrp: 55000, engine: "Electric, single/dual motor", hp: 225, torque: 258, trans: "Single-speed", fuel: 2.1, fuelReq: "Electric", range: 488, tank: null, drive: "AWD avail.", clearance: 160, length: 4655, seats: 5, cargo: 770, cargoMax: 1580, tow: 1000, carplay: "Wireless, standard", heated: "Seats & wheel std", screen: "Dual 12.3\"", adas: "SmartSense + HDA", blindSpot: "Standard", rearAeb: "Avail. (upper trims)", cam360: "Avail. (upper trims)", airbags: null, safetyRating: null, warranty: W_HYU, features: "800V ultra-fast charging, NACS port" },
  { id: "equinoxev26", make: "Chevrolet", label: "2026 Chevrolet Equinox EV", msrp: 45000, engine: "Electric, single/dual motor", hp: 213, torque: 236, trans: "Single-speed", fuel: 2.1, fuelReq: "Electric", range: 513, tank: null, drive: "AWD avail.", clearance: 170, length: 4837, seats: 5, cargo: 745, cargoMax: 1614, tow: null, carplay: "No CarPlay (Google built-in)", heated: "Seats & wheel std", screen: "17.7\"", adas: "Super Cruise avail.", blindSpot: "Avail.", rearAeb: "—", cam360: "Avail. (upper trims)", airbags: null, safetyRating: null, warranty: "3 yr/60,000 km (8/160 battery)", features: "Range for the money — but no CarPlay" },
];

export const SPEC_DISCLAIMER = "2026 model year, base trims, Canadian market — specs and pricing are approximate; confirm current details at the dealership.";
